import Head from 'next/head'
import Footer from '../Components/Footer'
import NavBar from '../Components/NavBar'

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Best Wedding planning company in delhi | Top 10  wedding planner company in India</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.wedcell.com/assets/front/images/favicon.ico" />
      </Head>

      <NavBar/>
      <main className={''}>
        <div className="">Main Content</div>
      </main>
      <Footer/>
    </div>
  )
}
